services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=habbit-tracker'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgre'
    ports:
      - '5432:5432'
